server:
  port: 8100

spring:
  profiles:
    active: native
  application:
    name: config-server
  #rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
  cloud:
    config:
      server:
        native:
          search-locations: file:///F:/config/dctp_config

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
